name: Build and Push Frontend

on:
  push:
    branches:
      - main  # or whichever branch you want
    paths:
      - 'frontend/sci-guard-web/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/sci-guard-web
          file: ./frontend/sci-guard-web/Dockerfile
          push: true
          tags: leeadams/sci-guard-frontend:latest

      - name: Trigger Render deploy
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
